site_name: TransMAP Hub
site_url: https://castuofa.github.io/transmap-docs/
repo_name: transmap-docs
repo_url: https://github.com/castuofa/transmap-docs
edit_uri: ""

# change directory names here
docs_dir: docs
site_dir: site

theme:
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  name: material
  icon:
      repo: fontawesome/brands/github
      logo: material/dns
      # fun logos! see https://material.io/icons/
  features:
      - navigation.instant
      - navigation.expand
      # - navigation.tabs
      - search.highlight
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          #   execute: True

markdown_extensions:
    - attr_list
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true
    - admonition
    - codehilite
    - extra
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format ''
    - pymdownx.tabbed

# give a title for each page
nav:
  - 'About the Project': 'index.md'
  - 'Architecture': 'architecture.md'
  - 'TransMAP Hub Explorer':
    - 'Usage': 'explorer_usage.md'
    - 'Use Cases': 'explorer_use_cases.md'
  - 'TransMAP Hub Analytics': 'placeholder.md'
  - 'TransMAP Python API': 'placeholder.md'
  - 'Data Sources':
    - 'Demographic': 'data_demographic.md'
    - 'Maritime': 'data_maritime.md'
    - 'Hydrographic': 'data_hydrographic.md'
    - 'Administrative Boundaries': 'data_administrative.md'