site_name: TransMAP Hub
site_url: http://castuofa.github.io/transmap-docs
repo_name: transmap-docs
repo_url: https://github.com/castuofa/transmap-docs
edit_uri: ""

# change directory names here
docs_dir: docs
site_dir: site

theme:
  palette:
      scheme: preference
  name: material
  icon:
      repo: fontawesome/brands/github
      logo: material/dns
      # fun logos! see https://material.io/icons/
  features:
      - navigation.instant
      - navigation.expand
      # - navigation.tabs
      - search.highlight

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'green'
    accent: 'purple'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          #   execute: True

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# give a title for each page
nav:
  - 'TransMAP': 'index.md'
  - 'About the Project': 'about.md'
  - 'Data Sources':
    - 'Demographic': 'data_demographic.md'
    - 'Maritime': 'data_maritime.md'
    - 'Hydrographic': 'data_hydrographic.md'
    - 'Administrative Boundaries': 'data_administrative.md'
  - 'TransMAP Hub Explorer':
    - 'Usage': 'explorer_usage.md'
    - 'Use Cases': 'explorer_use_cases.md'
  - 'TransMAP Hub Analytics': 'placeholder.md'
  - 'TransMAP Python API': 'placeholder.md'