site_name: TransMAP Hub
site_url: https://castuofa.github.io/transmap/
repo_name: transmap
repo_url: https://github.com/castuofa/transmap
edit_uri: ""

# change directory names here
docs_dir: docs
site_dir: site

theme:
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  name: material
  icon:
      repo: fontawesome/brands/github
      logo: material/dns
      # fun logos! see https://material.io/icons/
  features:
      - navigation.instant
      - navigation.expand
      # - navigation.tabs
      - search.highlight
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - render_swagger
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          #   execute: True

markdown_extensions:
    - attr_list
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true
    - admonition
    - codehilite
    - extra
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format ''
    - pymdownx.tabbed

# give a title for each page
nav:
  - 'About the Project': 'index.md'
  - 'Quickstart Guide': 'quickstart.md'
  - 'Use Cases':
    - 'Use Case: One': 'use_cases/one.md'
    - 'Use Case: Two': 'use_cases/two.md'
    - 'Use Case: Three': 'use_cases/three.md'
    - 'Coverage Matrix': 'use_cases/matrix.md'
  - 'TransMAP Hub Architecture': 'architecture.md'
  - 'TransMAP Hub Explorer': 'explorer/explorer.md'
  #   - 'Usage': 'explorer_usage.md'
  #   - 'Use Cases': 'explorer_use_cases.md'
  - 'TransMAP REST API': 'rest/api.md'
  - 'TransMAP Analytics Hub': 'analytics/analytics.md'
  - 'TransMAP Metadata Hub': 'geonetwork.md'
  # - 'TransMAP Python API': 'placeholder.md'
  #- 'Data Collections':
  #  - 'Vessel Movement': 'datasources/maritime_movement.md'
  #  - 'Multi-modal Networks': 'datasources/networks.md'
  #  - 'Navigation': 'datasources/navigation.md'
  #  - 'Environmental': 'datasources/environment.md'
  #  - 'Social & Demographic': 'datasources/demographic.md'
  #- 'Notebooks':
  #  - notebooks/notebooks/ais_traffic.ipynb
  #  - notebooks/notebooks/lock_analysis.ipynb
