# Database connection
DbConnection = "user=you host=localhost dbname=yourdb"

# Close pooled connections after this interval
DbPoolMaxConnLifeTime = "1h"

# Hold no more than this number of connections in the database pool
DbPoolMaxConns = 12
DbTimeout = 60

# Look to read html templates from this directory
AssetsPath = "./assets"

# Accept connections on this subnet (default accepts on all subnets)
HttpHost = "0.0.0.0"

# Accept connections on this port
HttpPort = 7800

# Advertise URLs relative to this server name
# default is to look this up from incoming request headers
UrlBase = "http://localhost:7800/tiles"

# Resolution to quantize vector tiles to
DefaultResolution = 4096

# Rendering buffer to add to vector tiles
DefaultBuffer = 256

# Limit number of features requested (-1 = no limit)
MaxFeaturesPerTile = 15000

# Advertise this minimum zoom level
DefaultMinZoom = 0

# Advertise this maximum zoom level
DefaultMaxZoom = 22

# Allow any page to consume these tiles
CORSOrigins = ["*"]

# Extra logging information?
Debug = false

# Set all urls to this subpath
# BasePath = "tiles"